config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "main#index"

  resources :accounts
  resource :session
  resources :users do
    post :google_sign_in, on: :collection
    delete :logout
  end
  resources :instagram_accounts, only: [] do
    get :form_fields, on: :collection
  end
  resources :bluesky_accounts, only: [] do
    get :form_fields, on: :collection
  end
  resources :share_codes, only: [ :new, :create, :destroy, :show ]
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  # skip_before_action :require_authentication

  def index
    if share_code.present?
      @share_code.increment!(:hits)
      @account = share_code.share_code_protectable
      @sharable_view = true
      render template: "accounts/show"
    end
  end

  private

  def share_code
    return unless root_params[:sc].present?

    @share_code ||= ShareCode.find_by(code: root_params[:sc])
  end

  def root_params
    params.permit(:sc)
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/index.html.erb
<% if notice %><p class="notice alert alert-primary p-2 my-3"><%= notice %></p><% end %>

<div class="container mt-5 p-3 rounded-3 header-box home-header-box">
  <div class="row justify-content-center">
    <div class="col-auto text-center">
      <h1>Anseo Anois</h1>
      <p><i>Here Now | Ici Maintenant | Aquí Ahora</i></p>
      <p>
        A link-as-a-service (LaaS) provider for internet account changes!
      </p>
      <p>
        <% if @current_user %>
          <%= link_to "View accounts", accounts_path, class: "btn btn-secondary fw-semibold" %>
          <%= link_to "Add account", new_account_path, class: "btn btn-warning fw-semibold" %>
        <% else %>
          <%= link_to "Login/Register", new_user_path, class: "btn btn-warning fw-semibold" %>
        <% end %>
      </p>
    </div>
  </div>
</div>