config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "main#index"

  resources :accounts
  resource :session
  resources :users do
    post :google_sign_in, on: :collection
    delete :logout
  end
  resources :instagram_accounts, only: [] do
    get :form_fields, on: :collection
  end
  resources :bluesky_accounts, only: [] do
    get :form_fields, on: :collection
  end
  resources :share_codes, only: [ :new, :create, :destroy, :show ]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sessions, dependent: :destroy
  has_many :accounts, foreign_key: :owner_id, inverse_of: :owner, dependent: :destroy
  has_many :account_replacements, inverse_of: :creator, foreign_key: :creator_id, dependent: :destroy
  has_many :replacements, through: :account_replacements, foreign_key: :owner_id
  has_many :replaced, through: :account_replacements, foreign_key: :owner_id
  has_many :instagram_accounts, through: :accounts, source: :accountable, source_type: "InstagramAccount"
  has_many :bluesky_accounts, through: :accounts, source: :accountable, source_type: "BlueskyAccount"
  has_many :share_codes, as: :share_code_protectable, dependent: :destroy
  has_many :owned_share_codes, class_name: "ShareCode", foreign_key: :creator_id, dependent: :destroy

  normalizes :email, with: ->(e) { e.strip.downcase }

  def owner
    self
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_current_user
  allow_unauthenticated_access only: %i[ new create ]
  before_action :insist_on_registered_user, only: %i[ show ]

  before_action :validate_google_csrf, only: :google_sign_in

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      start_new_session_for @user
      redirect_to "/"
    else
      render :new, status: :unprocessable_entity
    end
  end
  def show
    @user = User.find(params[:id])
  end

  def google_sign_in
    payload = Google::Auth::IDTokens.verify_oidc(params[:credential], aud: ENV["GOOGLE_CLIENT_ID"])
    return render json: { error: "Email not verified" }, status: :unauthorized unless payload["email_verified"]
    set_user_from_google_sign_in(payload)
    start_new_session_for @user
    redirect_to accounts_path
  rescue Google::Auth::IDTokens::SignatureError, Google::Auth::IDTokens::AudienceMismatchError
    render json: { error: "Invalid Google OAuth2 token" }, status: :unauthorized
  end

  def logout
    @current_user.sessions.destroy_all
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

  def validate_google_csrf
    return if cookies["g_csrf_token"].present? && params["g_csrf_token"].present? && cookies["g_csrf_token"] == params["g_csrf_token"]

    raise ActionController::InvalidAuthenticityToken, "CSRF token mismatch"
  end

  def set_user_from_google_sign_in(payload)
    @user = User.find_by(email: payload["email"])
    if @user
      User.update(name: payload["name"])
    else
      User.create(email: payload["email"], name: payload["name"])
    end
  end
end

app/views/users/_form.html.erb
<%= bootstrap_form_with(model: user) do |form| %>
    <% if user.errors.any? %>
        <div style="color: red">
            <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
            
            <ul>
                <% user.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div>
        <%= form.text_field :name %>
    </div>

    <div>
        <%= form.text_field :email %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
    <p>
        <strong>Email address:</strong>
        <%= user.email %>
    </p>
    <p>
        <strong>Created at:</strong>
        <%= user.created_at %>
    </p>
</div>

app/views/users/edit.html.erb
<% content_for :title, "Editing user" %>

<h1>Editing user</h1>

<% render "form", user: @user %>

<br>

<div>
    <%= link_to 'Back', users_path, class:"btn btn-secondary" %>
</div>

app/views/users/index.html.erb
<% if notice %><p class="notice alert alert-primary p-2"><%= notice %></p><% end %>

<% content_for :title, "Users" %>

<h2>Users</h2>

<div class="my-3">
    <%= link_to 'New User', new_user_path, class: "btn btn-primary" %>
</div>

<div id="users">
    <% @users.each do |user| %>
        <%= render user %>
        <p>
            <%= link_to 'Show', user %>
        </p>
    <% end %>
</div>

app/views/users/new.html.erb
<% content_for :title, "New user" %>

<h2>Login/register</h2>

<p>
     Anseo Anois supports Google sign-in. Only your name and email address will be used from Google.
</p>

<%# <%= render "form", user: @user %> 

<div id="g_id_onload"
     data-client_id="<%= ENV["GOOGLE_SIGN_IN_CLIENT_ID"] %>"
     data-context="signup"
     data-ux_mode="popup"
     data-login_uri="https://<%= ENV["SITE_DOMAIN"] %>/users/google_sign_in"
     data-authenticity_token="<%= form_authenticity_token %>"
     data-auto_select="true"
     data-itp_support="true"
</div>

<div class="g_id_signin"
     data-type="standard"
     data-shape="rectangular"
     data-theme="outline"
     data-text="signin_with"
     data-size="large"
     data-logo_alignment="left">
</div>

<%= javascript_include_tag "https://accounts.google.com/gsi/client", async: true, nonce: true %>

app/views/users/show.html.erb
<% if notice %><p class="notice alert alert-primary p-2"><%= notice %></p><% end %>

<%= render @user %>

<%= button_to "Logout", user_logout_path(@user), method: :delete, class: "btn btn-danger", turbo: false %>