config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "main#index"

  resources :accounts
  resource :session
  resources :users do
    post :google_sign_in, on: :collection
    delete :logout
  end
  resources :instagram_accounts, only: [] do
    get :form_fields, on: :collection
  end
  resources :bluesky_accounts, only: [] do
    get :form_fields, on: :collection
  end
  resources :share_codes, only: [ :new, :create, :destroy, :show ]
end

app/models/account.rb
class Account < ApplicationRecord
  DELEGATED_TYPES = [ InstagramAccount, BlueskyAccount ]

  delegated_type :accountable, types: DELEGATED_TYPES.map(&:name), dependent: :destroy
  accepts_nested_attributes_for :accountable

  belongs_to :owner, class_name: "User", inverse_of: :accounts
  has_many :replacement_records, class_name: "AccountReplacement", foreign_key: :replaced_id, inverse_of: :replaced
  has_many :replacements, through: :replacement_records, source: :replacement
  has_many :replaced_records, class_name: "AccountReplacement", foreign_key: :replacement_id, inverse_of: :replacement
  has_many :replaced, through: :replaced_records, source: :replaced
  has_many :share_codes, as: :share_code_protectable, dependent: :destroy

  delegate :platform_name, :menu_name, :account_name, :url, to: :accountable, allow_nil: true

  def solo?
    replacements.none? && replaced.none?
  end

  def url
    accountable.url
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[ show edit update destroy ]
  before_action :insist_on_registered_user

  # GET /accounts or /accounts.json
  def index
    @accounts = current_user.accounts
  end

  # GET /accounts/1 or /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = current_user.accounts.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts or /accounts.json
  def create
    @account = current_user.accounts.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: "Account was successfully created." }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1 or /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: "Account was successfully updated." }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1 or /accounts/1.json
  def destroy
    @account.destroy!

    respond_to do |format|
      format.html { redirect_to accounts_path, status: :see_other, notice: "Account was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.expect(account: [ :publicly_visible, :accountable_type, accountable_attributes: {}, replaced_ids: [], replacement_ids: [] ])
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_account.html.erb
<div id="<%= dom_id account %>">
  <% if @sharable_view %>
    <div class="container text-center my-3">
      <%= link_to "/", class: "text-decoration-none text-dark" do %>
        <h1 class="princess-sofia-regular">Anseo Anois</h2>
      <% end %>
    </div>
  <% end %>

  <% unless @sharable_view %>
    <h2><%= account.menu_name %></h2>
  <% end %>

  <%= render partial: "accounts/card_presentation", locals: { account: } %>

  <% if account.owner == @current_user && !@sharable_view %>
    <br>
    <%= render partial: "accounts/share_codes", locals: { account: } %>
    <br>
    <%= render partial: "accounts/owner_details", locals: { account: } %>
  <% end %>

  <% if @sharable_view %>
    <div class="container mt-2">
      <div class="row text-center">
        <p class="text-muted"><small>Anseo Anois is a Link-as-a-Service (LaaS) platform. <%= link_to "Add your accounts today!", new_account_path, class: "footer-link" %></small></p>
      </div>
    </div>
  <% end %>
</div>

app/views/accounts/_card_presentation.html.erb
<div class="container border border-2 rounded-3 p-4">
    <div class="row m-0 d-flex justify-content-center">
        <% if account.replaced.any? %>
        <div class="col-auto accounts-container replaced-accounts">
            <% account.replaced.each do |acc| %>
            <%= render acc.accountable, role: :replaced %>
            <% end %>
        </div>
        <%= render partial: "accounts/moved_to" %>
        <% end %>
        <% if account.solo? %>
        <div class="col-auto accounts-container solo-account">
            <%= render account.accountable, role: :current %>
        </div>
        <% else %>
            <div class="col-auto accounts-container <%= account.replacements.any? ? "current-replaced-account" : "replacement-accounts" %>">
                <%= render account.accountable, role: :current %>
            </div>
        <% end %>
        <% if account.replacements.any? %>
        <%= render partial: "accounts/moved_to" if account.replacements.any? %>
        <div class="col-auto accounts-container replacement-accounts">
            <% account.replacements.each do |acc| %>
            <%= render acc.accountable, role: :replacement %>
            <% end %>
        </div>
        <% end %>
    </div>
</div>

app/views/accounts/_form.html.erb
<%= bootstrap_form_with(model: account) do |form| %>
  <% if account.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
        <% account.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if !account.accountable.present? %>
    <div data-controller="account">
      <div>
        <%= form.select :accountable_type,
          options_for_select(Account::DELEGATED_TYPES.map { |klass| [klass.platform_name, klass.name] }),
          {prompt: 'Select a platform', label: 'Platform'},
          {data: {action: "change->account#change"}}
        %>
      </div>
      <%= turbo_frame_tag 'form_fields' %>
  <% else %>
    <br>
    <div>
      <%= form.label :accountable_type, 'Platform' %>
      <p>
        <i><%= account.accountable.class.platform_name %></i>
      </p>
    </div>
    <%= render partial: "#{account.accountable.class.name.underscore.pluralize}/form_fields", account: account %>
  <% end %>
    <br>

  <div>
    <%= form.collection_select :replaced_ids, @current_user.accounts.excluding(account), :id, :menu_name, {label: "This account has replaced:", multiple: true} %>
  </div>

  <div>
    <%= form.collection_select :replacement_ids, @current_user.accounts.excluding(account), :id, :menu_name, {label: "The replacements for this account are:",multiple: true} %>
  </div>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/_moved_to.html.erb
<div class="col-md-1 d-flex moved-to-image-container">
    <%= image_tag "arrow.png", class: "img-fluid moved-to-image" %>
</div>

app/views/accounts/_owner_details.html.erb
<div class="container border border-2 rounded-3 p-4">
    <h5>Account details</h3>
    <p>
      <strong>This account:</strong>
      <%= link_to account.menu_name, account, class: "badge text-bg-secondary" %>
    </p>

    <p>
      <strong>Replaced:</strong>
      <% account.replaced.each do |acc| %>
        <%= link_to acc.menu_name, acc, class: "badge text-bg-warning" %>
      <% end %>
    </p>

    <p>
    <strong>Replacements:</strong>
    <% account.replacements.each do |acc| %>
      <%= link_to acc.menu_name, acc, class: "badge text-bg-success" %>
    <% end %>
    </p>
</div>

app/views/accounts/_share_codes.html.erb
<div class="container border border-2 rounded-3 p-4">
    <h5>Share codes</h3>
    <div class="container share-codes-container">
        <div id="<%= dom_id(account, :share_codes) %>">
            <% account.share_codes.sort_by(&:hits).reverse.each do |share_code| %>
                <%= render "share_codes/share_code", share_code: %>
            <% end %>
        </div>
        <br>
    </div>
    <%= turbo_frame_tag "new_share_code" do %>
        <%= link_to "New share code", new_share_code_path(share_code_protectable_id: account.id, share_code_protectable_type: account.class.name), class: "btn btn-success" %>
    <% end %>
</div>

app/views/accounts/edit.html.erb
<% content_for :title, "Editing account" %>

<h1>Editing account</h1>

<%= render "form", account: @account %>

<div>
  <%= link_to "Show this account", @account %> |
  <%= link_to "Back to accounts", accounts_path %>
</div>

app/views/accounts/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Accounts" %>
<div class="container mt-5 p-4 rounded-3 header-box">
  <div class="row justify-content-center">
    <div class="col-auto text-center">
      <h2>Your accounts</h2>
      An account can be any kind of internet account, such as a social media account, messaging account, or any other kind of online presence.
      <br>
      <br>
      <%= link_to "Add account", new_account_path, class: "btn btn-warning fw-semibold" %>
    </div>
  </div>
</div>

<div id="accounts">
  <% @accounts.each do |account| %>
    <div class="container border border-3 border-dark-subtle rounded-3 p-4 my-5">
    <%= render account %>
    <br>
      <p>
      <%= link_to "Go to this account", account, class: "btn btn-primary" %>
      <%= button_to "Delete this account", account, method: :delete, class: "btn btn-danger d-inline-block" %>
    </p>
    </div>
  <% end %>
</div>

app/views/accounts/new.html.erb
<% content_for :title, "New account" %>

<h1>New account</h1>

<%= render "form", account: @account %>

<br>

<div>
  <%= link_to "Back to accounts", accounts_path, class: "btn btn-secondary" %>
</div>

app/views/accounts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @account %>

<% if @account.owner == @current_user && !@sharable_view %>
  <br>
  <div>
    <%= link_to "Edit this account", edit_account_path(@account), class: "btn btn-primary" %>
    <%= button_to "Delete this account", @account, method: :delete, class: "btn btn-danger" %>
  </div>
<% end %>